### ISSUE TITLE
Moving Window when using hiddenInset titlebar

### ISSUE THREAD

**Issue by baris-inandi** [nativefier/nativefier#1115]
I am on MacOS and i cannot move the window when using ```--title-bar-style hiddenInset```. How can I enable moving window?

**Comment by axeII** [comment]
@baris-inandi have you found the answer? I have exactly the same problem.

**Comment by axeII** [comment]
Got it! You need to create css file and use `--inject my.css` file where:
```css
/* my.css */

/* find the area which you want to be dragable and find the class*/
.pinning-header {
-webkit-app-region: drag;
padding-top: 20px;
}

/* if there are items in the are which you don't want to be dragable */
.secondary-navigation {
-webkit-app-region: no-drag;
}

```
