### ISSUE TITLE
Support injecting fonts

### ISSUE THREAD

**Issue by fakhamatia** [nativefier/nativefier#915]
How can I set custom font or inject it?
I use [This](https://chrome.google.com/webstore/detail/fontara/dcjdhicepiklefpimapdkbaeoocniemc) extension on Chrome and its inject some CSS JS to change the default font for better appearance and readable text.
Because many popular sites do not use the proper Middle Eastern font like GitHub Twitter WhatsApp Medium

**Comment by ronjouch** [comment]
https://github.com/jiahaog/nativefier/blob/master/docs/api.md#inject

**Comment by fakhamatia** [comment]
@ronjouch 
I know how inject css and js
how inject font folder?
I can inject font-face.css
But where I put font.woff ?

**Comment by ronjouch** [comment]
Ah, you want to inject a **local** font. Not sure it will work right now given the way resources are injected. Give it a try, search existing issues, look at the code. If all fails, comment here and I'll re-open as feature request.

**Comment by fakhamatia** [comment]
I try this but not work
``` bash
nativefier --name WhatsApp --counter --show-menu-bar --tray start-in-tray --single-instance --file-download-options '{"saveAs": true}' --zoom 1.2 --inject ./fix.js --inject ./font.css "https://web.whatsapp.com/"
```
[fix.js](https://github.com/jiahaog/nativefier/issues/852#issuecomment-587437705) for fix [this](https://github.com/jiahaog/nativefier/issues/852#issue-492640655)

``` css

@font-face {
    font-family: "Samim";
    src: url("../font/Samim-WOL.woff") format("woff");
    font-weight: normal
}

@font-face {
    font-family: "Samim";
    src: url("../font/Samim-Bold-WOL.woff") format("woff");
    font-weight: bold
}

body {
    font-family: "Samim", sans-serif !important;
    line-height: 1.7
}

body *[dir="rtl"] {
    font-family: "Samim", sans-serif !important;
    line-height: 1.7
}
```
Font path `WhatsApp-linux-x64/resources/app/inject/font/`

![ksnip_20200301-210826](https://user-images.githubusercontent.com/20030910/75630617-a28b9200-5c01-11ea-9add-d8dd3b2eacb0.png)
